function c = pickCjkFont()
%PICKCJKFONT  挑一个本机确实存在、且带 CJK 字形的字体（按平台给出中英文名）。
%
%   c = pickCjkFont()
%     Windows(中文版) → 微软雅黑 / Microsoft YaHei
%     Windows(英文版) → DengXian / SimHei
%     CentOS 7        → WenQuanYi Zen Hei / 文泉驿正黑
%     CentOS 7(最小)  → AR PL UMing CN / DejaVu Sans（兜底，可能缺个别汉字）
%
%   注意：元胞字面量里的续行符 '...' 后面不能跟注释，
%   否则注释会把续行符吞掉，行尾缺少 '...' 就会触发 catenate 维度错误。
%
%   纯函数，R2018b 兼容。

cands = { ...
    '微软雅黑', 'Microsoft YaHei', 'Microsoft YaHei UI', ...
    '等线', 'DengXian', ...
    'WenQuanYi Zen Hei', '文泉驿正黑', ...
    'WenQuanYi Micro Hei', '文泉驿微米黑', ...
    'Noto Sans CJK SC', 'Noto Sans SC', 'Noto Sans', ...
    'Source Han Sans CN', '思源黑体', ...
    'AR PL UMing CN', 'AR PL UKai CN', ...
    'SimHei', '黑体', 'SimSun', '宋体', 'DejaVu Sans'};
c = pickFont(cands);
end
